name: Parkour
author: SpleefLeague
authors: [Joba, Akaiyo, Manuman, NickM13]
main: com.spleefleague.parkour.Parkour
version: 1.0
depend: [SpleefLeagueCore, Commands, GameAPI]
commands:    
    parkour:
        description: Parkour queue command
        aliases: [superjump, sj, p]
        usage: |
          /<command> [mode] [arena]
          /<command> modes